- name: Playbook that installs minikube
  hosts: localhost
  user: ubuntu
  become: yes

  tasks: 
  - name: 1. Update apt packages
    become: yes
    apt:
      update_cache: yes
  - name: 2. Install Minikube and change permissions
    become: yes
    shell:
      cmd: curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
  - name: Update permissions
    become: yes
    shell:
      cmd: chmod +x minikube

  - name: 4. Move minikube to local/bin
    become: yes
    copy:
      src: minikube
      dest: /usr/local/bin/minikube
  - name: 5. Change chmod again
    become: yes
    shell:
      cmd: chmod +x /usr/local/bin/minikube
  # that fixes the error: Sorry, Kubernetes v1.18.2 requires conntrack to be installed in root's path #7

  - name: 6. Add contract files
    become: yes
    apt:
      name: conntrack
  - name: 7. Start minikube
    become: yes
    shell:
      cmd: minikube start --driver=none
     