- name: Playbook that installs minikube
  hosts: localhost
  user: ubuntu
  become: yes

  tasks: 
  - name: 1. Update apt packages
    apt:
      update_cache: yes
  - name: 2. Install Minikube and change permissions
    shell:
      cmd: curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
  - name: Update permissions
    shell:
      cmd: chmod +x minikube

  - name: 4. Move minikube to local/bin
    become: yes
    copy:
      src: minikube
      dest: /usr/local/bin/minikube
  - name: 5. Change chmod again
    shell:
      cmd: chmod +x /usr/local/bin/minikube
  - name: 5. Start minikube
    become: yes
    shell:
      cmd: minikube start 
     