- name: A playbook that scales in order to allow rolling changes
  hosts: localhost
  user: ubuntu
  become: yes

  tasks:
  - name: 1. Kubectl  scale  deployment with 5 replicas
    become: yes
    shell:
      cmd: kubectl scale deployments/coursework-deployment --replicas=5

  - name: 2. Get deployments
    become: yes
    shell:
      cmd: kubectl get deployments